export const RETRACT_SLIDER_MENU = 'RETRACT_SLIDER_MENU';
export const DETRACT_SLIDER_MENU = 'DETRACT_SLIDER_MENU';
export const FETCH_ALL_CURRENCIES = 'FETCH_ALL_CURRENCIES'; 
export const FETCH_ALL_CURRENCIES_SUCCESS = 'FETCH_ALL_CURRENCIES_SUCCESS';